### ISSUE TITLE
SM OR - A problem with <o:selectOneMenu> added dynamically

### ISSUE THREAD

**Issue by SlavaPk** [TeamDev-Ltd/OpenFaces#126] opened 2015-05-28 09:17 UTC
I try to add .xhtml part dynamically using API: faceletContext.includeFacelet(component, url);
Url - path to my .xhtml file with <o:selectOneMenu. 
The .xhtml file added but on commit I get exception:
![exception](https://cloud.githubusercontent.com/assets/12640347/7856577/db81b1d2-0532-11e5-95c2-a62b28ee0eb4.png)
If I use h:selectOneMenu or p:selectOneMenu everything works properly.
Used jsf version is 2.0.3

**Comment by YurinM** [comment] 2015-06-22 10:22
Duplicate of #121. mojarra has updated to version 2.0.4.

**Closed by YurinM** 2015-06-22 10:22 UTC
